# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./SourceCode/Detected/detected.h \
    ./SourceCode/PPTControl/CarryMove.h \
    ./SourceCode/PPTControl/keyboard.h \
    ./SourceCode/PPTControl/mouse.h \
    ./SourceCode/PPTControl/pptControl.h \
    ./SourceCode/PPTControl/PPtController.h \
    ./SourceCode/mainwindow.h \
    ./SourceCode/CameraThreadController.h \
    ./SourceCode/FileThreadController.h \
    ./SourceCode/socketwindow.h
SOURCES += ./SourceCode/Detected/detected.cpp \
    ./SourceCode/PPTControl/CarryMove.cpp \
    ./SourceCode/PPTControl/keyboard.cpp \
    ./SourceCode/PPTControl/mouse.cpp \
    ./SourceCode/PPTControl/pptControl.cpp \
    ./SourceCode/PPTControl/PPtController.cpp \
    ./SourceCode/socketwindow.cpp \
    ./SourceCode/CameraThreadController.cpp \
    ./SourceCode/FileThreadController.cpp \
    ./SourceCode/mainwindow.cpp \
    ./SourceCode/main.cpp
FORMS += ./SourceCode/mainwindow.ui \
    ./SourceCode/socketwindow.ui
TRANSLATIONS += ./mainwindow_zh.ts
RESOURCES += SourceCode/mainwindow.qrc
